load("ext://helm_resource", "helm_resource", "helm_repo")

# version_settings() enforces a minimum Tilt version
# https://docs.tilt.dev/api.html#api.version_settings
version_settings(constraint='>=0.30.0')

# Where the redirect URI should go to, for example
EXTERNAL_URL = "http://localhost:65432"


# disable Quickstart bootstrap
os.putenv('QUICKSTART_BOOTSTRAP_DISABLED', 'True')

# Where helm values for examples
os.putenv('HELM_VALUES_PATH', '../examples/helm/')

# start Quickstart
# https://docs.tilt.dev/api.html#api.include
# Versions of things backend to pull (attributes, kas, etc)
load('../quickstart/Tiltfile', "BACKEND_CHART_TAG")

# execute Examples bootstrap
helm_resource(
    "bootstrap",
    "oci://ghcr.io/opentdf/charts/keycloak-bootstrap",
    flags=[
        "--version",
        BACKEND_CHART_TAG,
        "-f",
        "helm/values-bootstrap.yaml",
        "--set",
        "externalUrl=%s" % EXTERNAL_URL,
    ],
    labels="examples",
    resource_deps=["attributes", "entitlements", "keycloak"],
)
