#!/usr/bin/env bash
# Generate `offline-bundle` zipfile for installing OpenTDF cluster in an intranet.
#
# This bundle contains:
#   * opentdf-service-images.tar, containing all microservices
#   * third-party-images.tar, useful third party images
#   * Client libraries and scripts
#   * TK Helm charts for deploying the servicesin a k8s cluster
#
# Parameters:
#    MONOLOG_LEVEL: 0 = Debug logging
#    BACKEND_IMAGE_TAG: tag to apply to all backend images (kas, attribute and entity services)
#    BACKEND_CHART_TAG: tag to apply to all backend charts
#    FRONTEND_IMAGE_TAG: tag to apply to all frontend images (abacus)
#    FRONTEND_CHART_TAG: tag to apply to all backend charts

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
export PATH="$PATH:$APP_DIR:$PROJECT_ROOT/scripts"

monolog TRACE "Running [$0${1+ }$*]"

clean_first=
build_total_image=
no_charts=
no_clients=
no_images=
no_first_party=
no_third_party=
no_zip=

while [[ $# -gt 0 ]]; do
  key="$1"
  shift

  case "$key" in
    --clean)
      monolog TRACE "--clean"
      clean_first=1
      ;;
    --oci)
      monolog TRACE "--oci"
      build_total_image=1
      ;;
    --no-charts)
      monolog TRACE "--no-charts"
      no_charts=1
      ;;
    --no-clients)
      monolog TRACE "--no-clients"
      no_clients=1
      ;;
    --no-images)
      monolog TRACE "--no-images"
      no_images=1
      ;;
    --no-first-party)
      monolog TRACE "--no-first-party"
      no_first_party=1
      ;;
    --no-third-party)
      monolog TRACE "--no-third-party"
      no_third_party=1
      ;;
    --no-zip)
      monolog TRACE "--no-zip"
      no_zip=1
      ;;
    *)
      monolog ERROR "Unrecognized option: [$key]"
      exit 1
      ;;
  esac
done

if ! cd "$PROJECT_ROOT"; then
  monolog ERROR "Unable to find project root [${PROJECT_ROOT}] from APP_DIR=[${APP_DIR}]"
  exit 1
fi

today="$(date +%Y-%m-%d)"
digest="$(git rev-parse --short HEAD)"
suffix="${today}-${digest}"
: "${OUTPUT_DIRECTORY:="${PROJECT_ROOT}/build/export"}"

# TODO Default to image tags in chart values files
: "${BACKEND_IMAGE_TAG:="1.2.1"}"
# FIXME Update with release version
: "${BACKEND_CHART_TAG:="1.2.1"}"
: "${FRONTEND_IMAGE_TAG:="1.2.0"}"
: "${FRONTEND_CHART_TAG:="1.2.0"}"

# TODO(PLAT-1417) add 'storage' once published to ghcr.io
services=(abacus attributes entitlement_store entitlement-pdp entitlements entity-resolution kas keycloak-bootstrap)
charts=("${services[@]}")
charts[2]=entitlement-store

chart_tags=("${FRONTEND_CHART_TAG}" "${BACKEND_CHART_TAG}"{,,,,,,})
image_tags=("${FRONTEND_IMAGE_TAG}" "${BACKEND_IMAGE_TAG}"{,,,,,,})

OUT_DIR="${OUTPUT_DIRECTORY}/bundle"

if [[ $clean_first ]]; then
  monolog INFO "Cleaning old bundle folder, [${OUT_DIR}]"
  if [ ! -d "${OUT_DIR}" ]; then
    monolog INFO "Directory not found (already clean): [${OUT_DIR}]"
    exit 1
  elif ! rm -r "${OUT_DIR}"; then
    monolog ERROR "Failure when deleting [${OUT_DIR}]"
    exit 1
  fi
fi

mkdir -p "${OUT_DIR}/charts"
mkdir -p "${OUT_DIR}/lib"
mkdir -p "${OUT_DIR}/containers"

export BACKEND_IMAGE_TAG

echo "${suffix}" >"$OUT_DIR/BUNDLE_TAG"

# Save an image to a file: repo tag outfile-prefix
save-image() {
  monolog TRACE "save-image [$*]"
  local short_name
  local name_tag
  local image
  short_name="$1"
  name_tag="$2"
  image="${short_name}:${name_tag}"

  monolog TRACE "save-image [docker pull $image]"
  if ! docker pull "$image"; then
    monolog ERROR "Failed to pull docker image ${image}"
    exit 1
  fi

  local outprefix
  outprefix="$3"

  local path
  local tar_path
  local version

  path="${OUT_DIR}/containers/${outprefix}-${suffix}"
  tar_path="${path}.tar"
  version="$(docker inspect --format='{{index .RepoDigests 0}}' "${image}")"
  monolog TRACE "save-image [docker save -o ${tar_path} ${image}]"
  if ! docker save -o "${tar_path}" "${image}"; then
    monolog ERROR "Failed to save docker image [${image}] as [${tar_path}]"
    exit 1
  fi
  # Required information for tagging image locally
  monolog TRACE "save-image [echo $version $image >${path}.meta]"
  if ! echo "$version" "$image" >"${path}.meta"; then
    monolog ERROR "Failed to save tag metadata for docker image [${image}] to [${path}.meta]"
    exit 1
  fi
}

if [[ ! $no_first_party && ! $no_images ]]; then
  monolog DEBUG "Saving first party images..."
  for index in "${!services[@]}"; do
    save-image "ghcr.io/opentdf/${services[$index]}" "${image_tags[$index]}" "opentdf-${services[$index]}"
  done
fi

# NOTE: Configure third party bundles to use the latest version manually.
# To do this, search for the version you want of each of the following packages
# on Docker Hub
if [[ ! $no_third_party && ! $no_images ]]; then
  monolog DEBUG "Saving third party images..."
  # KIND: https://kind.sigs.k8s.io/docs/user/working-offline/
  # Update URI: https://hub.docker.com/r/kindest/node/tags
  save-image kindest/node v1.23.5 third-party-image-kind

  # postgresql
  # Update URI: https://hub.docker.com/r/bitnami/postgresql/tags
  save-image bitnami/postgresql 11.14.0-debian-10-r28 third-party-image-postgresql

  # Keycloak: We are using a custom image with entitlement support
  save-image "ghcr.io/opentdf/keycloak" 19.0.2 "opentdf-keycloak"

  # nginx ingress
  save-image k8s.gcr.io/ingress-nginx/controller v1.1.1 third-party-image-ingress-nginx

  # docker registry
  save-image registry 2.7.1 third-party-image-docker-registry
fi

if [[ ! $no_third_party && ! $no_charts ]]; then
  monolog DEBUG "Saving third party charts..."
  if ! helm pull --repo https://kubernetes.github.io/ingress-nginx --version 4.0.16 --destination "${OUT_DIR}/charts" ingress-nginx; then
    monolog ERROR "Unable to helm pull ingress-nginx"
    exit 1
  fi
  if ! helm pull --repo https://codecentric.github.io/helm-charts --version 1.6.1 --destination "${OUT_DIR}/charts" keycloakx; then
    monolog ERROR "Unable to helm pull keycloak"
    exit 1
  fi
  if ! helm pull --repo https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami --version 12.1.8 --destination "${OUT_DIR}/charts" postgresql; then
    monolog ERROR "Unable to helm pull postgresql"
    exit 1
  fi
  if ! helm pull --repo https://helm.twun.io --version 2.1.0 --destination "${OUT_DIR}/charts" docker-registry; then
    monolog ERROR "Unable to helm pull twuni/docker-registry"
    exit 1
  fi
fi

if [[ ! $no_first_party && ! $no_charts ]]; then
  monolog DEBUG "Saving first party charts..."
  for index in "${!charts[@]}"; do
    chart="${charts[$index]}"
    url="oci://ghcr.io/opentdf/charts/${chart}"
    tag="${chart_tags[$index]}"
    if ! helm pull "${url}" --version "${tag}" --destination "${OUT_DIR}/charts"; then
      monolog ERROR "Failed to [helm pull ${url} --version $tag]"
      exit 1
    fi
  done
fi

# Include an example deployment
if ! rsync -lmr --safe-links --executability --force quickstart "${OUT_DIR}"; then
  monolog ERROR "Unable to update quickstart"
  exit 1
fi

# Include scripts for helping with things
if ! rsync -lmr --safe-links --executability --force scripts "${OUT_DIR}"; then
  monolog ERROR "Unable to update scripts folder"
  exit 1
fi

if ! cp examples/offline/docker-load-and-tag-exports "${OUT_DIR}"/scripts; then
  monolog ERROR "Unable to update image load script"
  exit 1
fi

maybe-exit() {
  local err="$?"
  if [[ ! $err ]]; then
    monolog ERROR "$1; err=$err"
    exit 1
  fi
}

# # # DOWNLOAD SOME SDKS
# TODO(PLAT-1417) Get @opentdf/client from npm
npm-latest() {
  local project
  project="$1"
  shift

  local NPM_LATEST
  NPM_LATEST=$(curl -s http://registry.npmjs.org/"${project}"/latest/ | sed 's/.*"tarball":"\([^"]*\).*/\1/')

  local NPM_TGZ
  NPM_TGZ=$(echo "$NPM_LATEST" | sed 's/.*-\/\(.*\.tgz\)$/\1/')
  curl -s "https://registry.npmjs.org/${project}/-/$NPM_TGZ" --output "${OUT_DIR}/lib/sdk-$NPM_TGZ"
  maybe-exit "Failed to get latest of ${project} (${NPM_LATEST}) from NPM, expected at [${NPM_TGZ}]"
}

pip-latest() {
  local project
  project="$1"
  shift

  local deets
  deets="$(curl -s "https://pypi.org/pypi/${project}/json")"
  maybe-exit "Getting details of [${project}] failed with $?"

  local version
  version="$(jq -r '.info.version' <<<"${deets}")"
  maybe-exit "Getting latest version of [${project}] failed"

  local variants
  variants=$(jq -r --arg version "$version" '.releases[$version]' <<<"${deets}")
  maybe-exit "Getting latest version of [${project}] failed"

  local len
  len=$(jq -r 'length' <<<"$variants")
  maybe-exit "Surprising variants object"
  [[ $len ]]
  maybe-exit "len=[$len]"
  monolog INFO "Found $len variants of $project $version"

  local filename
  local url
  for ((i = 0; i < len; i++)); do
    filename=$(jq -r --argjson i "$i" '.[$i].filename' <<<"${variants}")
    url=$(jq -r --argjson i "$i" '.[$i].url' <<<"${variants}")
    [[ $filename && $url ]]
    maybe-exit "filename=[$filename] url=[$url]"
    monolog INFO "Downloading $filename from $url"
    curl -s "${url}" >"${OUT_DIR}/lib/${filename}"
    maybe-exit "Failed downloading [$url]"
  done
}

if [[ ! $no_clients ]]; then
  # # TODO: Release client to npm
  # npm-latest @opentdf/client

  pip-latest opentdf
fi

# BUNDLE THAT STUFF UP
if [[ ! $no_zip ]]; then
  fname="offline-bundle-${suffix}.tgz"
  if ! (cd "${OUTPUT_DIRECTORY}" && tar -czf "${fname}" bundle); then
    monolog ERROR "Failed to export as tgz file"
    exit 1
  fi
  monolog DEBUG "Saved stuff as ${OUTPUT_DIRECTORY}/${fname}"
fi

echo "${suffix}" >"${OUT_DIR}"/COMPLETED_TAG

if [[ $build_total_image ]]; then
  docker buildx build -t opentdf/offline-demo:"${suffix}" -f examples/offline/Dockerfile "${OUT_DIR}"
fi
