# Tiltfile for development
# https://docs.tilt.dev/api.html
#

load("ext://helm_resource", "helm_resource", "helm_repo")

# Where the redirect URI should go to, for example
EXTERNAL_URL = "http://localhost:65432"

# Versions of things backend to pull (attributes, kas, etc)
BACKEND_CHART_TAG = "1.1.1"
FRONTEND_CHART_TAG = "1.1.1"

# disable Quickstart bootstrap
os.putenv('QUICKSTART_BOOTSTRAP_DISABLED', 'True')

# Where helm values for examples
os.putenv('HELM_VALUES_PATH', '../examples/helm')

include('../../quickstart/Tiltfile')

# execute Examples bootstrap
helm_resource(
    "keycloak-bootstrap",
    "oci://ghcr.io/opentdf/charts/keycloak-bootstrap",
    flags=[
        "--version",
        BACKEND_CHART_TAG,
        "-f",
        "../helm/values-bootstrap.yaml",
        "--set",
        "externalUrl=%s" % EXTERNAL_URL,
    ],
    labels="utility",
    resource_deps=["attributes", "entitlements", "keycloak"],
)

#k8s_resource("kas", resource_deps=["opentdf-attributes"], port_forwards="8000:8000")

# frontend
k8s_yaml("kubernetes.yaml")
k8s_resource(
    "opentdf-abacship",
    resource_deps = ["keycloak-bootstrap"],
    labels="abacship",
)

docker_build(
    "opentdf/abacship",
    "."
)

#backend
docker_build(
    "opentdf/abacship-backend",
    "./backend_server"
)

abacship_backend_set = [
    "image.name=opentdf/abacship-backend"
    ]

k8s_yaml(
    helm(
        "backend_server/helm",
        "abacship-backend",
        set=abacship_backend_set,
        values=["backend_server/deployment/abacship-backend-values.yaml"],
    )
)

k8s_resource(
   "abacship-backend", 
    resource_deps=["keycloak-bootstrap"],
    labels="abacship"
)


# local_resource(
#     "opentdf-abacship-backend",
#     cmd = "./backend_server/scripts/setup_venv.sh",
#     serve_cmd = "cd backend_server/src && \
#     source ./venv/bin/activate && \
#     python3 -m uvicorn main:app --reload --port 4060",
#     labels="abacship",
#     resource_deps = ["keycloak-bootstrap"],
#     allow_parallel=True
# )

